version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        config:
          loaded_at_field: date # specify column name to use for freshness check 
          freshness:
            warn_after: {count: 1, period: hour} # warning after 1 hours
            error_after: {count: 24, period: hour} # fail after 24 hours. 
            # CI/CD pipeline would fail if this was integrated into it and data has not been refreshed in the past 24 hours 